---
# yaml-language-server:$schema=https://json.schemastore.org/github-workflow.json
on:  # yamllint disable-line rule:truthy
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run bats test
        run: |
          ./run_tests.sh
